gym/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('gym_app.urls')),
]

gym_app/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
      path('registerAdmin', registerAdmin, name='registerAdmin'),
      path('', loginAdmin, name='loginAdmin'),
      path('home', home, name='home'),
      path('logout', logoutAdmin, name='logout'),
      path('addMember', addMember, name='addMember'),
      path('updateMember/<str:pk>', updateMember, name='updateMember'),
      path('deleteMember/<str:pk>', deleteMember, name='deleteMember'),
      path('plans', plans, name='plans'),
      path('addPlan', addPlan, name='addPlan'),
      path('updatePlan/<str:pk>', updatePlan, name='updatePlan'),
      path('deletePlan/<str:pk>', deletePlan, name='deletePlan'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_name = 'gym_app'

gym_app/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime as dt
from django.utils import timezone 
from datetime import datetime, timedelta
# Create your models here.

# User.add_to_class(
#       'email', models.EmailField(null=False,blank=False)
# )

class Plans(models.Model):
      plan_id     = models.AutoField(primary_key=True)
      plan_name   = models.CharField(max_length=255, blank=True, null=True)
      description = models.TextField(blank=True, null=True)
      price       = models.IntegerField(blank=True, null=True)
      duration    = models.IntegerField(blank=True, null=True)

      def __str__(self) -> str:
            return self.plan_name
      class Meta:
            app_label = 'gym_app'

class Member(models.Model):
      member_id   = models.AutoField(primary_key=True)
      first_name  = models.CharField(max_length=255, blank=True, null=True)
      last_name   = models.CharField(max_length=255, blank=True, null=True)
      city        = models.CharField(max_length=100, blank=True, null=True)
      zipcode     = models.IntegerField(blank=True, null=True)
      phoneno     = models.IntegerField(blank=True, null=True)
      bought_on   = models.DateField(blank=True, null=True)
      # plan        = models.ForeignKey(Plans, on_delete=models.PROTECT)
      plan        = models.ForeignKey(Plans, null=True, blank=True, on_delete=models.SET_NULL)

      @property
      def expires_in(self):

            bought = self.bought_on
            try:
                  duration = int(self.plan.duration)
            except Exception as e:
                  return "PLAN DELETED"
            # date = dt.date(2023, 1, 12)
            # delta = bought - date
            delta = bought - datetime.now().date()
            days_left = duration + delta.days
            return days_left

      class Meta:
            app_label = 'gym_app'

gym_app/forms.py
from django.core import validators
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from django.contrib.admin.widgets import AdminDateWidget

from .models import Member, Plans

# class AdminRegister(forms.ModelForm):
      # def __init__(self, *args, **kwargs):
      #   super().__init__(*args, **kwargs)

      #   for field in self.Meta.required:
      #       self.fields[field].required = True

#       class Meta:
#             model = User
#             fields = ['email', 'password']
            # error_messages = {'email':{'required':'Email is required'},
            #                   'passowrd':{'required':'Password is required'}
            #                   ,}
#             widgets = {'email': forms.EmailInput, 'password':forms.PasswordInput}
#             required = ('email', 'password')

class AdminSignupForm(UserCreationForm):

      email     = forms.CharField(required=True, widget=forms.EmailInput(attrs={'class':"form-control"}))
      username  = forms.CharField(required=True, label='Username', widget=forms.TextInput(attrs={'class':'form-control'}))
      password1 = forms.CharField(required=True,label='Password', widget=forms.PasswordInput(attrs={'class':"form-control"}))
      password2 = forms.CharField(required=True,label='Confirm Password', widget=forms.PasswordInput(attrs={'class':"form-control"}))

      class Meta:
            model  = User
            fields = ['username', 'email', 'password1', 'password2']
            error_messages = {'email':{'required':'Email is required'},
                  'passowrd':{'required':'Password is required'}
                  ,}
            labels = {'email':'Email', 'password1':'Password'}


class AddMemberForm(forms.ModelForm):
      

      first_name  = forms.CharField(widget=forms.TextInput(attrs={'class':"form-control"}))
      last_name   = forms.CharField(widget=forms.TextInput(attrs={'class':"form-control"}))
      city        = forms.CharField(widget=forms.TextInput(attrs={'class':"form-control"}))
      zipcode     = forms.IntegerField(widget=forms.TextInput(attrs={'class':"form-control"}))
      phoneno     = forms.IntegerField(widget=forms.TextInput(attrs={'class':"form-control"}))
      bought_on   = forms.DateField(widget=forms.DateInput(attrs={'type':'date','name':'bought_on'}))
      # plan        = forms.ChoiceField(widget=forms.Select(attrs={'class':"custom-select"}))
      plan      = forms.ModelChoiceField(queryset=Plans.objects.all(), widget=forms.Select(attrs={'name':'plan_id'}))

      class Meta:
            model   = Member
            fields  = ['first_name', 'last_name', 'city', 'zipcode', 'phoneno', 'bought_on', 'plan']
            labels  = {'first_name':'First Name', 'last_name': 'Last Name', 'city':'City', 'zipcode':'Zipcode', 'plan':'Plans'}
            # widgets = {'plan': forms.}

      

class AddPlan(forms.ModelForm):
      plan_name    = forms.CharField(widget=forms.TextInput(attrs={'class':"form-control"}))
      description  = forms.CharField(widget=forms.Textarea(attrs={'class':"form-control"}))
      price        = forms.IntegerField(widget=forms.NumberInput(attrs={'class':"form-control"}))
      duration     = forms.IntegerField(widget=forms.NumberInput(attrs={'class':"form-control"}))
      class Meta:
            model = Plans
            fields = ['plan_name', 'description', 'price', 'duration']
            lables = {'plan_name':'Plan Name', 'description':'Description', 'price':'Price', 'duration':'Duration'}

gym_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db import transaction
# from django.contrib.auth.forms import UserCreationForm
from .forms import AdminSignupForm, AddMemberForm, AddPlan
from .models import Member, Plans
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.contrib.auth.hashers import check_password


##############  REGISTER ADMIN  ##################
@transaction.atomic
def registerAdmin(request):
      if request.method == 'POST':
            form = AdminSignupForm(request.POST)
            if form.is_valid():
                  messages.success(request, 'Account Created!!')
                  # User.objects.create(email=request.POST.get('email'), password=request.POST.get('password'))
                  form.save()

                  context = {'form':form}
                  return redirect('gym_app:loginAdmin', permanent=True)
            else:
                  context = {'form': form}
                  return render(request, 'gym_app/pages/registerAdmin.html', context)
      else:
            form = AdminSignupForm()
            context = {'form':form}
            return render(request, 'gym_app/pages/registerAdmin.html', context)


##############  LOGIN ADMIN  ########################
@transaction.atomic
def loginAdmin(request):
      
      if request.user.is_authenticated:
            return redirect('gym_app:home', permanent=True)

      if request.method == 'POST':
            email = request.POST.get('email')
            password = request.POST.get('password')
            # user = authenticate(email=email, password=password)
            try:
                  user = User.objects.get(email=email)
            except User.DoesNotExist:
                  return render(request, 'gym_app/pages/loginAdmin.html', context={'message':'Invalid Credentials.'})
            if check_password(password, user.password):
                  if user.is_active:
                        login(request, user)
                        return redirect('gym_app:home', permanent=True)
            return render(request, 'gym_app/pages/loginAdmin.html', context={'message':'Invalid Credentials.'})
      return render(request, 'gym_app/pages/loginAdmin.html')


##############  HomePage  ######################
@login_required(login_url="/")
def home(request):
      if request.method == 'GET':
            members = Member.objects.all()
            context = {'members':members}

            return render(request, 'gym_app/pages/home.html', context)

##############  Adding a new member  ####################
@login_required(login_url="/")
@transaction.atomic
def addMember(request):
      if request.method == 'GET':
            fm = AddMemberForm()
            plans = Plans.objects.all()
            context = {'title': 'Add Member', 'form':fm, 'plans':plans, 'button':'Add Member'}
            return render(request, 'gym_app/pages/addMember.html', context)

      elif request.method == 'POST':
            fm = AddMemberForm(request.POST)

            if fm.is_valid():
                  fm.save()
                  return redirect('gym_app:home', permanent=True)
            # return render(request, 'gym_app/pages/addMember.html')
            return redirect('gym_app:addMember', permanent=True)


##############  Updating a member  ####################
@login_required(login_url="/")
@transaction.atomic
def updateMember(request, pk):
      
      member = Member.objects.filter(member_id=pk).first()
      fm = AddMemberForm(instance=member)
      context = {'form':fm, 'button':'Update Member'}
            
      if request.method == 'POST':
            fm = AddMemberForm(request.POST, instance=member)
            
            if fm.is_valid():
                  fm.save()
                  return redirect('gym_app:home', permanent=True)
      return render(request, 'gym_app/pages/addMember.html', context)


##############  Deleting a member  ####################
@login_required(login_url="/")
def deleteMember(request, pk):
      member = Member.objects.filter(member_id=pk).first()
      if member is not None:
            member.delete()
      return redirect('gym_app:home', permanent=True)


##############  List of All Membership Plans  ####################
@login_required(login_url="/")
def plans(request):
      plans = Plans.objects.all()
      context = {'title': 'Add Member', 'plans':plans}
      return render(request, 'gym_app/pages/plans.html', context)


##############  Adding a New Membership Plan  #######################
@login_required(login_url="/")
@transaction.atomic
def addPlan(request):

      fm = AddPlan()
      context = {'title': 'Add Plan', 'form':fm}
      
      
      if request.method == 'POST':
            plan = AddPlan(request.POST)
            if plan.is_valid():
                  plan.save()
                  
                  return redirect('gym_app:plans', permanent=True)
      return render(request, 'gym_app/pages/addPlan.html', context)


##############  Updating a Membership Plan  ####################
@login_required(login_url="/")
@transaction.atomic
def updatePlan(request, pk):
      plan = Plans.objects.filter(plan_id=pk).first()
      fm = AddPlan(instance=plan)
      context = {'form':fm, 'button':'Update Member'}
      if request.method == 'POST':
            fm = AddPlan(request.POST, instance=plan)

            if fm.is_valid():
                  fm.save()
                  return redirect('gym_app:plans', permanent=True)
      return render(request, 'gym_app/pages/addPlan.html', context)


##############  Delete a Membership Plan  ####################
@login_required(login_url="/")
@transaction.atomic
def deletePlan(request, pk):
      plans = Plans.objects.filter(plan_id=pk).first()
      if plans is not None:
            plans.delete()
      return redirect('gym_app:plans', permanent=True)

##############  Logout  ########################
@login_required(login_url="/")
@transaction.atomic
def logoutAdmin(request):
      logout(request)
      return redirect('gym_app:loginAdmin', permanent=True)

gym_app/templates/gym_app/pages/addMember.html
{% extends '../layout/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{{title}}</title>
</head>
<body>
      {% block content %}
            <div class="form-group">
                  <form action="" method="post">
                        {% csrf_token %}
                        
                        <!-- First Name input -->
                        <div class="form-outline mb-4">
                              <!-- <label class="form-label" for="form3Example3">First Name</label> -->
                              {{form.first_name.label_tag}}
                              {{form.first_name}}
                              <!-- <input type="text" name={{form.name.first_name}} id="id_first_name" class="form-control" /> -->
                              <!-- {{fm.label}}: {{fm}} -->
                              <!-- {{form.first_name.}} -->
                        </div>

                        <!-- Second Name input -->
                        <div class="form-outline mb-4">
                              <!-- <label class="form-label" for="form3Example3">First Name</label> -->
                              {{form.last_name.label_tag}}
                              {{form.last_name}}
                              <!-- <input type="text" name={{form.name.last_name}} id="id_last_name" class="form-control" /> -->
                              <!-- {{fm.label}}: {{fm}} -->
                              <!-- {{form.first_name.}} -->
                        </div>
                        
                        <!-- City input -->
                        <div class="form-outline mb-4">
                              <!-- <label class="form-label" for="form3Example3">First Name</label> -->
                              {{form.city.label_tag}}
                              {{form.city}}
                              <!-- <input type="text" name={{form.name.city}} id="id_city" class="form-control" /> -->
                              <!-- {{fm.label}}: {{fm}} -->
                              <!-- {{form.first_name.}} -->
                        </div>

                        <div class="form-outline mb-4">
                              {{form.zipcode.label_tag}}
                              {{form.zipcode}}
                        </div>

                        <div class="form-outline mb-4">
                              {{form.phoneno.label_tag}}
                              {{form.phoneno}}
                        </div>

                        <div class="form-outline mb-4">
                              {{form.bought_on.label_tag}}
                              {{form.bought_on}}
                        </div>

                        <div class="form-outline mb-4">
                              {{form.plan.label_tag}}
                              {{form.plan}}
                              
                        </div>
                        <!-- <input type="submit" value="Add Member"> -->
                        <button type="submit" class="btn btn-primary btn-block mb-4">{{button}}</button>
                  </form>
            </div>
      {% endblock %}
</body>
</html>

gym_app/templates/gym_app/pages/home.html
{% extends '../layout/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{{title}}</title>

      {% block style %}
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      {% endblock %}
</head>

<body>
      {% block content %}
            <br><br><br>
            <!-- Tabs navs -->
            <ul class="nav nav-tabs nav-justified mb-3" id="ex1" role="tablist">
                  <li class="nav-item" role="presentation">
                        <a class="nav-link active" id="ex1-tab-1" data-bs-toggle="tab" href="#ex1-tabs-1" role="tab"
                              aria-controls="ex1-tabs-1" aria-selected="true">Active Members</a>
                  </li>
                  <li class="nav-item" role="presentation">
                        <a class="nav-link" id="ex1-tab-2" data-bs-toggle="tab" href="#ex1-tabs-2" role="tab"
                              aria-controls="ex1-tabs-2" aria-selected="false">Expiring Member Plans</a>
                  </li>
                  <li class="nav-item" role="presentation">
                        <a class="nav-link" id="ex1-tab-3" data-bs-toggle="tab" href="#ex1-tabs-3" role="tab"
                              aria-controls="ex1-tabs-3" aria-selected="false">All Members</a>
                  </li>
            </ul>
            <!-- Tabs navs -->
            
            <!-- Tabs content -->
            <div class="tab-content" id="ex1-content">
                  <div class="tab-pane fade show active" id="ex1-tabs-1" role="tabpanel" aria-labelledby="ex1-tab-1">
                        <div class="data">
                              <h2>Active Members</h2>
                              <table class="table">
                                    <thead>
                                          <tr>
                                                <th scope="col">First Name</th>
                                                <th scope="col">Last Name</th>
                                                <th scope="col">City</th>
                                                <th scope="col">Zipcode</th>
                                                <th scope="col">Phone No.</th>
                                                <th scope="col">Plan</th>
                                                <th scope="col">Bought On</th>
                                                <th scope="col">Expires In</th>
                                                <th scope="col">Edit</th>
                                                <th scope="col">Delete</th>
            
            
                                          </tr>
                                    </thead>
                                    <tbody>
                                          {% for item in members %}
                                          {% if item.expires_in > 7 %}
                                                <tr> 
                                                      <td> {{item.first_name}} </td>
                                                      <td> {{item.last_name}} </td>
                                                      <td> {{item.city}} </td>
                                                      <td> {{item.zipcode}} </td>
                                                      <td> {{item.phoneno}} </td>
                                                      <td> 
                                                            {% if item.plan.plan_name is none %}
                                                                  <p>PLAN DELETED</p>
                                                            {% else %}
                                                            {{item.plan.plan_name}}
                                                            {% endif %}       
                                                      </td>
                                                      <td> {{item.bought_on}} </td>
                                                      <td> {{item.expires_in}} </td>
                                                      <td> <a href="{% url 'gym_app:updateMember' item.member_id %}" > <button class="btn btn-light"><i class="fa-solid fa-pen-to-square"></i></button> </a> </td>
                                                      <!-- <td><a data-toggle="modal" href="#deleteModal" ><i class="fa-solid fa-trash"></i></a></td> -->
                                                      <!-- <td><button > <a href="{% url 'gym_app:updateMember' item.member_id %}"><i class="fa-solid fa-pen-to-square"></i></a> </button></td> -->
                                                      <td> <a href="{% url 'gym_app:deleteMember' item.member_id %}" ><button type="button" class="btn btn-light"><i class="fa-solid fa-trash"></i></button></a></td>
                                                </tr>
            
                                          {% endif %}
                                          {% endfor %}
                                    </tbody>
                              </table>
                        </div>
                  </div>
                  <div class="tab-pane fade" id="ex1-tabs-2" role="tabpanel" aria-labelledby="ex1-tab-2">
                        <div class="data">
                              <h2>Expiring Plans (Within 7 days)</h2>
                              <table class="table">
                                    <thead>
                                          <tr>
                                                <th scope="col">First Name</th>
                                                <th scope="col">Last Name</th>
                                                <th scope="col">City</th>
                                                <th scope="col">Zipcode</th>
                                                <th scope="col">Phone No.</th>
                                                <th scope="col">Plan</th>
                                                <th scope="col">Bought On</th>
                                                <th scope="col">Expires In</th>
                                                <th scope="col">Edit</th>
                                                <th scope="col">Delete</th>
            
            
                                          </tr>
                                    </thead>
                                    <tbody>
                                          {% for item in members %}
                                          {% if item.expires_in <= 7 and item.expires_in >= 0  %}
                                                <tr> 
                                                      <td> {{item.first_name}} </td>
                                                      <td> {{item.last_name}} </td>
                                                      <td> {{item.city}} </td>
                                                      <td> {{item.zipcode}} </td>
                                                      <td> {{item.phoneno}} </td>
                                                      <td> 
                                                            {% if item.plan.plan_name is none %}
                                                                  <p>PLAN DELETED</p>
                                                            {% else %}
                                                            {{item.plan.plan_name}}
                                                            {% endif %}
                                                      </td>
                                                      <td> {{item.bought_on}} </td>
                                                      <td> {{item.expires_in}} </td>
                                                      <td> <a href="{% url 'gym_app:updateMember' item.member_id %}" > <button class="btn btn-light"><i class="fa-solid fa-pen-to-square"></i></button> </a> </td>
                                                      <!-- <td><a data-toggle="modal" href="#deleteModal" ><i class="fa-solid fa-trash"></i></a></td> -->
                                                      <!-- <td><button > <a href="{% url 'gym_app:updateMember' item.member_id %}"><i class="fa-solid fa-pen-to-square"></i></a> </button></td> -->
                                                      <td> <a href="{% url 'gym_app:deleteMember' item.member_id %}" ><button type="button" class="btn btn-light"><i class="fa-solid fa-trash"></i></button></a></td>
                                                </tr>
            
                                          {% endif %}
                                          {% endfor %}
                                    </tbody>
                              </table>
                        </div>
                  </div>
                  <div class="tab-pane fade" id="ex1-tabs-3" role="tabpanel" aria-labelledby="ex1-tab-3">
                        <div class="data">
                              <h2>All Members</h2>
                              <table class="table">
                                    <thead>
                                          <tr>
                                                <th scope="col">First Name</th>
                                                <th scope="col">Last Name</th>
                                                <th scope="col">City</th>
                                                <th scope="col">Zipcode</th>
                                                <th scope="col">Phone No.</th>
                                                <th scope="col">Plan</th>
                                                <th scope="col">Bought On</th>
                                                <th scope="col">Expires In</th>
                                                <th scope="col">Edit</th>
                                                <th scope="col">Delete</th>
            
            
                                          </tr>
                                    </thead>
                                    <tbody>
                                          {% for item in members %}
                                                <tr> 
                                                      <td> {{item.first_name}} </td>
                                                      <td> {{item.last_name}} </td>
                                                      <td> {{item.city}} </td>
                                                      <td> {{item.zipcode}} </td>
                                                      <td> {{item.phoneno}} </td>
                                                      <td> {{item.plan.plan_name}} </td>
                                                      <td> {{item.bought_on}} </td>
                                                      <td> 
                                                            {% if item.expires_in < 0 %}
                                                                  EXPIRED
                                                            {% else %}
                                                                  {{item.expires_in}}
                                                            {% endif %}
                                                      </td>
                                                      <td> <a href="{% url 'gym_app:updateMember' item.member_id %}" > <button class="btn btn-light"><i class="fa-solid fa-pen-to-square"></i></button> </a> </td>
                                                      <!-- <td><a data-toggle="modal" href="#deleteModal" ><i class="fa-solid fa-trash"></i></a></td> -->
                                                      <!-- <td><button > <a href="{% url 'gym_app:updateMember' item.member_id %}"><i class="fa-solid fa-pen-to-square"></i></a> </button></td> -->
                                                      <td> <a href="{% url 'gym_app:deleteMember' item.member_id %}" ><button type="button" class="btn btn-light"><i class="fa-solid fa-trash"></i></button></a></td>
                                                </tr>
                                          {% endfor %}
                                    </tbody>
                              </table>
                        </div>
                  </div>
            </div>

            



      {% endblock %}
</body>
</html>

gym_app/templates/gym_app/pages/loginAdmin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Admin Login</title>

      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

      <link rel="stylesheet" href="{% static 'gym_app/css/loginAdmin.min.css' %}">
</head>
<body class="body-login">
      {{context}}
      {{message}}
      <br><br><br><br><br>
      <div class="post-form">
            <form method="post">
                  {% csrf_token %}
                  <div class="input-group">
                        <span class="input-group-text">Email</span>
                        <input type="text" name="email" class="form-control" required>
                  </div><br>
                  <div class="input-group">
                        <span class="input-group-text">Password</span>
                        <input type="password" name="password" class="form-control" required>
                  </div><br>
                  <!-- <input type="submit"><br> -->
                  <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
                  <br>
                  <span>Don't Have an Account?</span><a  href="{% url 'gym_app:registerAdmin' %}">Sign Up</a>
            </form>
      </div>
</body>
</html>

gym_app/templates/gym_app/pages/plans.html
{% extends '../layout/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{{title}}</title>

      {%block style%}
      <link rel="stylesheet" href="{% static 'gym_app/css/plan.min.css' %}">
      {% endblock %}
</head>
<body>

      {% block content %}
      <br><br><br><br>
      {% for plan in plans %}
      <div class="columns">
            <ul class="price">
                  <li class="header">{{plan.plan_name}}</li>
                  <li class="grey">$ {{plan.price}} for {{ plan.duration }} days</li>
                  <p> {{plan.description}} </p>
                  <li class="grey">
                        <a href="{% url 'gym_app:updatePlan' plan.plan_id %}" class="buttonEdit">Edit Plan</a>
                        <a href="{% url 'gym_app:deletePlan' plan.plan_id %}" class="buttonDelete">Delete Plan</a>
                  </li>
            </ul>
      </div>
      {% endfor %}
      {% endblock %}
</body>
</html>