gym/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('gym_app.urls')),
]

gym_app/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
      path('registerAdmin', registerAdmin, name='registerAdmin'),
      path('', loginAdmin, name='loginAdmin'),
      path('home', home, name='home'),
      path('logout', logoutAdmin, name='logout'),
      path('addMember', addMember, name='addMember'),
      path('updateMember/<str:pk>', updateMember, name='updateMember'),
      path('deleteMember/<str:pk>', deleteMember, name='deleteMember'),
      path('plans', plans, name='plans'),
      path('addPlan', addPlan, name='addPlan'),
      path('updatePlan/<str:pk>', updatePlan, name='updatePlan'),
      path('deletePlan/<str:pk>', deletePlan, name='deletePlan'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_name = 'gym_app'

gym_app/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime as dt
from django.utils import timezone 
from datetime import datetime, timedelta
# Create your models here.

# User.add_to_class(
#       'email', models.EmailField(null=False,blank=False)
# )

class Plans(models.Model):
      plan_id     = models.AutoField(primary_key=True)
      plan_name   = models.CharField(max_length=255, blank=True, null=True)
      description = models.TextField(blank=True, null=True)
      price       = models.IntegerField(blank=True, null=True)
      duration    = models.IntegerField(blank=True, null=True)

      def __str__(self) -> str:
            return self.plan_name
      class Meta:
            app_label = 'gym_app'

class Member(models.Model):
      member_id   = models.AutoField(primary_key=True)
      first_name  = models.CharField(max_length=255, blank=True, null=True)
      last_name   = models.CharField(max_length=255, blank=True, null=True)
      city        = models.CharField(max_length=100, blank=True, null=True)
      zipcode     = models.IntegerField(blank=True, null=True)
      phoneno     = models.IntegerField(blank=True, null=True)
      bought_on   = models.DateField(blank=True, null=True)
      # plan        = models.ForeignKey(Plans, on_delete=models.PROTECT)
      plan        = models.ForeignKey(Plans, null=True, blank=True, on_delete=models.SET_NULL)

      @property
      def expires_in(self):

            bought = self.bought_on
            try:
                  duration = int(self.plan.duration)
            except Exception as e:
                  return "PLAN DELETED"
            # date = dt.date(2023, 1, 12)
            # delta = bought - date
            delta = bought - datetime.now().date()
            days_left = duration + delta.days
            return days_left

      class Meta:
            app_label = 'gym_app'

gym_app/forms.py
from django.core import validators
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from django.contrib.admin.widgets import AdminDateWidget

from .models import Member, Plans

# class AdminRegister(forms.ModelForm):
      # def __init__(self, *args, **kwargs):
      #   super().__init__(*args, **kwargs)

      #   for field in self.Meta.required:
      #       self.fields[field].required = True

#       class Meta:
#             model = User
#             fields = ['email', 'password']
            # error_messages = {'email':{'required':'Email is required'},
            #                   'passowrd':{'required':'Password is required'}
            #                   ,}
#             widgets = {'email': forms.EmailInput, 'password':forms.PasswordInput}
#             required = ('email', 'password')

class AdminSignupForm(UserCreationForm):

      email     = forms.CharField(required=True, widget=forms.EmailInput(attrs={'class':"form-control"}))
      username  = forms.CharField(required=True, label='Username', widget=forms.TextInput(attrs={'class':'form-control'}))
      password1 = forms.CharField(required=True,label='Password', widget=forms.PasswordInput(attrs={'class':"form-control"}))
      password2 = forms.CharField(required=True,label='Confirm Password', widget=forms.PasswordInput(attrs={'class':"form-control"}))

      class Meta:
            model  = User
            fields = ['username', 'email', 'password1', 'password2']
            error_messages = {'email':{'required':'Email is required'},
                  'passowrd':{'required':'Password is required'}
                  ,}
            labels = {'email':'Email', 'password1':'Password'}


class AddMemberForm(forms.ModelForm):
      

      first_name  = forms.CharField(widget=forms.TextInput(attrs={'class':"form-control"}))
      last_name   = forms.CharField(widget=forms.TextInput(attrs={'class':"form-control"}))
      city        = forms.CharField(widget=forms.TextInput(attrs={'class':"form-control"}))
      zipcode     = forms.IntegerField(widget=forms.TextInput(attrs={'class':"form-control"}))
      phoneno     = forms.IntegerField(widget=forms.TextInput(attrs={'class':"form-control"}))
      bought_on   = forms.DateField(widget=forms.DateInput(attrs={'type':'date','name':'bought_on'}))
      # plan        = forms.ChoiceField(widget=forms.Select(attrs={'class':"custom-select"}))
      plan      = forms.ModelChoiceField(queryset=Plans.objects.all(), widget=forms.Select(attrs={'name':'plan_id'}))

      class Meta:
            model   = Member
            fields  = ['first_name', 'last_name', 'city', 'zipcode', 'phoneno', 'bought_on', 'plan']
            labels  = {'first_name':'First Name', 'last_name': 'Last Name', 'city':'City', 'zipcode':'Zipcode', 'plan':'Plans'}
            # widgets = {'plan': forms.}

      

class AddPlan(forms.ModelForm):
      plan_name    = forms.CharField(widget=forms.TextInput(attrs={'class':"form-control"}))
      description  = forms.CharField(widget=forms.Textarea(attrs={'class':"form-control"}))
      price        = forms.IntegerField(widget=forms.NumberInput(attrs={'class':"form-control"}))
      duration     = forms.IntegerField(widget=forms.NumberInput(attrs={'class':"form-control"}))
      class Meta:
            model = Plans
            fields = ['plan_name', 'description', 'price', 'duration']
            lables = {'plan_name':'Plan Name', 'description':'Description', 'price':'Price', 'duration':'Duration'}

gym_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db import transaction
# from django.contrib.auth.forms import UserCreationForm
from .forms import AdminSignupForm, AddMemberForm, AddPlan
from .models import Member, Plans
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.contrib.auth.hashers import check_password


##############  REGISTER ADMIN  ##################
@transaction.atomic
def registerAdmin(request):
      if request.method == 'POST':
            form = AdminSignupForm(request.POST)
            if form.is_valid():
                  messages.success(request, 'Account Created!!')
                  # User.objects.create(email=request.POST.get('email'), password=request.POST.get('password'))
                  form.save()

                  context = {'form':form}
                  return redirect('gym_app:loginAdmin', permanent=True)
            else:
                  context = {'form': form}
                  return render(request, 'gym_app/pages/registerAdmin.html', context)
      else:
            form = AdminSignupForm()
            context = {'form':form}
            return render(request, 'gym_app/pages/registerAdmin.html', context)


##############  LOGIN ADMIN  ########################
@transaction.atomic
def loginAdmin(request):
      
      if request.user.is_authenticated:
            return redirect('gym_app:home', permanent=True)

      if request.method == 'POST':
            email = request.POST.get('email')
            password = request.POST.get('password')
            # user = authenticate(email=email, password=password)
            try:
                  user = User.objects.get(email=email)
            except User.DoesNotExist:
                  return render(request, 'gym_app/pages/loginAdmin.html', context={'message':'Invalid Credentials.'})
            if check_password(password, user.password):
                  if user.is_active:
                        login(request, user)
                        return redirect('gym_app:home', permanent=True)
            return render(request, 'gym_app/pages/loginAdmin.html', context={'message':'Invalid Credentials.'})
      return render(request, 'gym_app/pages/loginAdmin.html')


##############  HomePage  ######################
@login_required(login_url="/")
def home(request):
      if request.method == 'GET':
            members = Member.objects.all()
            context = {'members':members}

            return render(request, 'gym_app/pages/home.html', context)

##############  Adding a new member  ####################
@login_required(login_url="/")
@transaction.atomic
def addMember(request):
      if request.method == 'GET':
            fm = AddMemberForm()
            plans = Plans.objects.all()
            context = {'title': 'Add Member', 'form':fm, 'plans':plans, 'button':'Add Member'}
            return render(request, 'gym_app/pages/addMember.html', context)

      elif request.method == 'POST':
            fm = AddMemberForm(request.POST)

            if fm.is_valid():
                  fm.save()
                  return redirect('gym_app:home', permanent=True)
            # return render(request, 'gym_app/pages/addMember.html')
            return redirect('gym_app:addMember', permanent=True)


##############  Updating a member  ####################
@login_required(login_url="/")
@transaction.atomic
def updateMember(request, pk):
      
      member = Member.objects.filter(member_id=pk).first()
      fm = AddMemberForm(instance=member)
      context = {'form':fm, 'button':'Update Member'}
            
      if request.method == 'POST':
            fm = AddMemberForm(request.POST, instance=member)
            
            if fm.is_valid():
                  fm.save()
                  return redirect('gym_app:home', permanent=True)
      return render(request, 'gym_app/pages/addMember.html', context)


##############  Deleting a member  ####################
@login_required(login_url="/")
def deleteMember(request, pk):
      member = Member.objects.filter(member_id=pk).first()
      if member is not None:
            member.delete()
      return redirect('gym_app:home', permanent=True)


##############  List of All Membership Plans  ####################
@login_required(login_url="/")
def plans(request):
      plans = Plans.objects.all()
      context = {'title': 'Add Member', 'plans':plans}
      return render(request, 'gym_app/pages/plans.html', context)


##############  Adding a New Membership Plan  #######################
@login_required(login_url="/")
@transaction.atomic
def addPlan(request):

      fm = AddPlan()
      context = {'title': 'Add Plan', 'form':fm}
      
      
      if request.method == 'POST':
            plan = AddPlan(request.POST)
            if plan.is_valid():
                  plan.save()
                  
                  return redirect('gym_app:plans', permanent=True)
      return render(request, 'gym_app/pages/addPlan.html', context)


##############  Updating a Membership Plan  ####################
@login_required(login_url="/")
@transaction.atomic
def updatePlan(request, pk):
      plan = Plans.objects.filter(plan_id=pk).first()
      fm = AddPlan(instance=plan)
      context = {'form':fm, 'button':'Update Member'}
      if request.method == 'POST':
            fm = AddPlan(request.POST, instance=plan)

            if fm.is_valid():
                  fm.save()
                  return redirect('gym_app:plans', permanent=True)
      return render(request, 'gym_app/pages/addPlan.html', context)


##############  Delete a Membership Plan  ####################
@login_required(login_url="/")
@transaction.atomic
def deletePlan(request, pk):
      plans = Plans.objects.filter(plan_id=pk).first()
      if plans is not None:
            plans.delete()
      return redirect('gym_app:plans', permanent=True)

##############  Logout  ########################
@login_required(login_url="/")
@transaction.atomic
def logoutAdmin(request):
      logout(request)
      return redirect('gym_app:loginAdmin', permanent=True)

gym_app/templates/gym_app/layout/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{{title}}</title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

      {% block style %}{% endblock %}

      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
      
</head>
<body>
      {% block header %}
            {% include './header.html' %}
      {% endblock %}

      <div class="container">
            <div class="row">

                  <div class="col-lg">

                        {% block content %}
                              This is content
                        {% endblock %}
                        <br><br><br><br>                        
                  </div>

                  <br><br><br><br>

                  <div class="row">
                        {% block footer %}
                              {% include './footer.html' with date="23 Nov 2022" var=1234%}
                        {% endblock %}
                  </div>
            </div>
      </div>
</body>
</html>

gym_app/templates/gym_app/layout/header.html
<nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'gym_app:home' %}">Logo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'gym_app:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'gym_app:addMember' %}">Add Member</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'gym_app:plans' %}">Membership Plans</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'gym_app:addPlan' %}">Add Plans</a>
            </li>
          </ul>
          <!-- <button>
            <a class="button" href="{% url 'gym_app:logout' %}">Logout</a>
          </button> -->
          <a class="nav-link" href="{% url 'gym_app:logout' %}">Logout</a>
        </div>
      </div>
    </nav>